name: NadirKitap Fiyat Karşılaştırma

on:
  schedule:
    # Her gün sabah 08:00 ve akşam 20:00 UTC’de çalıştırır.
    - cron:  "0 8,20 * * *"
  workflow_dispatch:

jobs:
  compare-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run price comparison
        run: |
          python nadirkitap_tracker.py
